name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    schedule:
      - cron: 0/5 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/merge-schedule-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME_ZONE: 'Asia/Tokyo'