name: Schedule Publish
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: */15 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}